Repository Baldrani/pres-lm-ia, pull requests merged in 2024-09, with the labels that each got.

#3 chore: add position
  src/drawBilboard.js
  src/slides/slides_ale.js
  src/slides/slides_anir.js
  src/slides/slides_mael.js
Labels: enhancement, Review effort [1-5]: 3

#5 chore: add typescript and rollup bundeling
  .babelrc
  .editorconfig
  .eslintignore
  .eslintrc.json
  .github/FUNDING.yml
  .github/workflows/nodejs.yml
  .github/workflows/pr-agent.yml
  .gitignore
  .prettierrc
  LICENSE
  README.md
  __tests__/main.test.ts
  eslint.config.js
  jest-preset.json
  jest.config.cjs
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  public/style.css
  rollup.config.js
  server.js
  src/app.js
  src/drawBilboard.js
  src/drawBilboard.ts
  src/index.html
  src/main.ts
  src/slides/index.js
  src/slides/index.ts
  src/slides/slides_ale.js
  src/slides/slides_ale.ts
  src/slides/slides_anir.js
  src/slides/slides_anir.ts
  src/slides/slides_mael.js
  src/slides/slides_mael.ts
  src/styles.css
  src/types/index.ts
  tests/app.test.js
  tsconfig.json
  tsconfig.release.json
Labels: documentation, enhancement, tests, Review effort [1-5]: 4

#6 chore: fix images display
  README.md
  package-lock.json
  package.json
  src/drawBilboard.ts
  src/main.ts
  src/slides/slides_mael.ts
Labels: documentation, enhancement, Review effort [1-5]: 3

#8 feat: add possibility to erase slide
  __tests__/__setups__/canvas.js
  jest.config.js
  src/drawBilboard.ts
  src/drawing.ts
  src/slides/slides_ale.ts
  src/slides/slides_mael.ts
  src/types/index.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#9 feat: add ale slides
  public/index.html
  src/drawing.ts
  src/slides/slides_ale.ts
Labels: enhancement, Review effort [1-5]: 2

#13 feat: add image and sound for slide test
  public/images/background.jpg
  public/images/coderabbit-flow.png
  public/images/codium.png
  public/index.html
  public/style.css
  src/drawing.ts
  src/slides/slides_ale.ts
  src/slides/slides_mael.ts
  src/types/index.ts
Labels: enhancement, Review effort [1-5]: 3, other

#14 feat: remove duplicate ale slides
  src/slides/slides_ale.ts
Labels: enhancement, Review effort [1-5]: 1
